[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm = { path = "../wasm" }
ast = { path = "../ast" }
clap = "4.5.9"
